export type WeatherIconProps = {
    icon: IconName,
    iconAlt: string,
    animate?: boolean,
};

export type IconObject = {
    normal: string,
    animated: string,
}

export type IconName = "rain"
    | "cloudy"
    | "clearDay"
    | "showery"
    | "mostlyClearDay"
    | "becomingUnsettled"
    | "stormy"
    | "improving"
    | "worsening"
    | "clear sky"
    | "few clouds"
    | "scattered clouds"
    | "broken clouds"
    | "shower rain"
    | "thunderstorm"
    | "snow"
    | "mist"
    | "clear sky night"
    | "few clouds night"
    | "scattered clouds night"
    | "broken clouds night"
    | "shower rain night"
    | "thunderstorm night"
    | "snow night"
    | "mist night"
    | "thunderstorm with light rain"
    | "thunderstorm with light rain night"
    | "thunderstorm with rain"
    | "thunderstorm with rain night"
    | "thunderstorm with heavy rain"
    | "thunderstorm with heavy rain night"
    | "light thunderstorm"
    | "light thunderstorm night"
    | "heavy thunderstorm"
    | "heavy thunderstorm night"
    | "ragged thunderstorm"
    | "ragged thunderstorm night"
    | "thunderstorm with light drizzle"
    | "thunderstorm with light drizzle night"
    | "thunderstorm with drizzle"
    | "thunderstorm with drizzle night"
    | "thunderstorm with heavy drizzle"
    | "thunderstorm with heavy drizzle night"
    | "light intensity drizzle"
    | "light intensity drizzle night"
    | "drizzle"
    | "drizzle night"
    | "heavy intensity drizzle"
    | "heavy intensity drizzle night"
    | "light intensity drizzle rain"
    | "light intensity drizzle rain night"
    | "drizzle rain"
    | "drizzle rain night"
    | "heavy intensity drizzle rain"
    | "heavy intensity drizzle rain night"
    | "shower rain and drizzle"
    | "shower rain and drizzle night"
    | "heavy shower rain and drizzle"
    | "heavy shower rain and drizzle night"
    | "shower drizzle"
    | "shower drizzle night"
    | "light rain"
    | "light rain night"
    | "moderate rain"
    | "moderate rain night"
    | "heavy intensity rain"
    | "heavy intensity rain night"
    | "very heavy rain"
    | "very heavy rain night"
    | "extreme rain"
    | "extreme rain night"
    | "freezing rain"
    | "freezing rain night"
    | "light intensity shower rain"
    | "light intensity shower rain night"
    | "shower rain"
    | "shower rain night"
    | "heavy intensity shower rain"
    | "heavy intensity shower rain night"
    | "ragged shower rain"
    | "ragged shower rain night"
    | "light snow"
    | "light snow night"
    | "snow"
    | "snow night"
    | "heavy snow"
    | "heavy snow night"
    | "sleet"
    | "sleet night"
    | "light shower sleet"
    | "light shower sleet night"
    | "shower sleet"
    | "shower sleet night"
    | "light rain and snow"
    | "light rain and snow night"
    | "shower snow"
    | "shower snow night"
    | "heavy shower snow"
    | "heavy shower snow night"
    | "rain and snow"
    | "rain and snow night"
    | "light shower snow"
    | "light shower snow night"
    | "overcast clouds"
    | "overcast clouds night"
    | "mist"
    | "mist night"
    | "smoke"
    | "smoke night"
    | "haze"
    | "haze night"
    | "sand/dust whirls"
    | "sand/dust whirls night"
    | "fog"
    | "fog night"
    | "sand"
    | "sand night"
    | "dust"
    | "dust night"
    | "volcanic ash"
    | "volcanic ash night"
    | "squalls"
    | "squalls night"
    | "tornado"
    | "tornado night"
    | "unknown"